PYTHON LIST

In [1]:
import datetime
import numpy as np

print("WITHOUT LOOP M1 = M2 + M3")
t1 = datetime.datetime.now()
print("t1:", t1)

M2 = [[2 for i in range(100)] for j in range(100)]
M3 = [[3 for i in range(100)] for j in range(100)]
M1 = M2 + M3

t2 = datetime.datetime.now()
print("t2:", t2)

print("TIME ELAPSED:", t2-t1)

print("M2:\n", M2)
print("M3:\n", M3)
print("M1:\n", M1)


WITHOUT LOOP M1 = M2 + M3
t1: 2024-02-11 18:47:13.271940
t2: 2024-02-11 18:47:13.272935
TIME ELAPSED: 0:00:00.000995
M2:
 [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [2]:
import datetime

print("ROW MAJOR LOOPS R-C")
t1 = datetime.datetime.now()
print("t1:", t1)

M2 = [[2 for i in range(100)] for j in range(100)]
M3 = [[3 for i in range(100)] for j in range(100)]
M1 = [[0 for i in range(100)] for j in range(100)]

for i in range(100):
    for j in range(100):
        M1[i][j] = M2[i][j] + M3[i][j]

t2 = datetime.datetime.now()
print("t2:", t2)

print("TIME ELAPSED:", t2-t1)

print("M2:", M2)
print("M3:" ,M3)
print("M1:",M1)

ROW MAJOR LOOPS R-C
t1: 2024-02-11 18:47:44.543517
t2: 2024-02-11 18:47:44.552176
TIME ELAPSED: 0:00:00.008659
M2: [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 

In [3]:
import datetime

print("COLUMN MAJOR LOOPS C-R")
t1 = datetime.datetime.now()
print("t1:", t1)

M2 = [[2 for i in range(100)] for j in range(100)]
M3 = [[3 for i in range(100)] for j in range(100)]
M1 = [[0 for i in range(100)] for j in range(100)]

for j in range(100):
    for i in range(100):
        M1[i][j] = M2[i][j] + M3[i][j]

t2 = datetime.datetime.now()
print("t2:", t2)

print("TIME ELAPSED:", t2-t1)

print("M2:", M2)
print("M3:" ,M3)
print("M1:",M1)

COLUMN MAJOR LOOPS C-R
t1: 2024-02-11 18:47:58.043159
t2: 2024-02-11 18:47:58.055844
TIME ELAPSED: 0:00:00.012685
M2: [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 

PYTHON - NUMPY

In [4]:
import datetime
import numpy as np

print("NUMPY - WITHOUT LOOP M1 = M2 + M3")
t1 = datetime.datetime.now()
print("t1:", t1)

M2 = np.array([[2 for i in range(100)] for j in range(100)])
M3 = np.array([[3 for i in range(100)] for j in range(100)])
M1 = M2 + M3

t2 = datetime.datetime.now()
print("t2:", t2)

print("TIME ELAPSED:", t2-t1)

print("M2:\n", M2)
print("M3:\n", M3)
print("M1:\n", M1)

NUMPY - WITHOUT LOOP M1 = M2 + M3
t1: 2024-02-11 18:48:11.939834
t2: 2024-02-11 18:48:11.946667
TIME ELAPSED: 0:00:00.006833
M2:
 [[2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 ...
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]]
M3:
 [[3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
M1:
 [[5 5 5 ... 5 5 5]
 [5 5 5 ... 5 5 5]
 [5 5 5 ... 5 5 5]
 ...
 [5 5 5 ... 5 5 5]
 [5 5 5 ... 5 5 5]
 [5 5 5 ... 5 5 5]]


In [5]:
import datetime
import numpy as np

print("NUMPY - ROW MAJOR LOOPS R-C")
t1 = datetime.datetime.now()
print("t1:", t1)

M2 = np.array([[2 for i in range(100)] for j in range(100)])
M3 = np.array([[3 for i in range(100)] for j in range(100)])

M1 = np.empty((100, 100))

for i in range(100):
    for j in range(100):
        M1[i][j] = M2[i][j] + M3[i][j]

t2 = datetime.datetime.now()
print("t2:", t2)

print("TIME ELAPSED:", t2-t1)

print("M2:", M2)
print("M3:" ,M3)
print("M1:",M1)

NUMPY - ROW MAJOR LOOPS R-C
t1: 2024-02-11 18:48:39.144767
t2: 2024-02-11 18:48:39.173485
TIME ELAPSED: 0:00:00.028718
M2: [[2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 ...
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]]
M3: [[3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
M1: [[5. 5. 5. ... 5. 5. 5.]
 [5. 5. 5. ... 5. 5. 5.]
 [5. 5. 5. ... 5. 5. 5.]
 ...
 [5. 5. 5. ... 5. 5. 5.]
 [5. 5. 5. ... 5. 5. 5.]
 [5. 5. 5. ... 5. 5. 5.]]


In [6]:
import datetime
import numpy as np

print("NUMPY - COLUMN MAJOR LOOPS C-R")
t1 = datetime.datetime.now()
print("t1:", t1)

M2 = np.array([[2 for i in range(100)] for j in range(100)])
M3 = np.array([[3 for i in range(100)] for j in range(100)])

M1 = np.empty((100, 100))

for j in range(100):
    for i in range(100):
        M1[i][j] = M2[i][j] + M3[i][j]

t2 = datetime.datetime.now()
print("t2:", t2)

print("TIME ELAPSED:", t2-t1)

print("M2:", M2)
print("M3:" ,M3)
print("M1:",M1)

NUMPY - COLUMN MAJOR LOOPS C-R
t1: 2024-02-11 18:48:57.122740
t2: 2024-02-11 18:48:57.161669
TIME ELAPSED: 0:00:00.038929
M2: [[2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 ...
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]]
M3: [[3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
M1: [[5. 5. 5. ... 5. 5. 5.]
 [5. 5. 5. ... 5. 5. 5.]
 [5. 5. 5. ... 5. 5. 5.]
 ...
 [5. 5. 5. ... 5. 5. 5.]
 [5. 5. 5. ... 5. 5. 5.]
 [5. 5. 5. ... 5. 5. 5.]]
